services:
  postgres-reminders:
    image: postgres:16-alpine
    ports:
      - 1801:5432
    volumes:
      - uservice_reminders_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  uservice_reminders_postgres:
