// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-reminders/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetReminderRepository is an autogenerated mock type for the GetReminderRepository type
type MockGetReminderRepository struct {
	mock.Mock
}

type MockGetReminderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetReminderRepository) EXPECT() *MockGetReminderRepository_Expecter {
	return &MockGetReminderRepository_Expecter{mock: &_m.Mock}
}

// GetReminder provides a mock function with given fields: ctx, author, target, publicIdentifier
func (_m *MockGetReminderRepository) GetReminder(ctx context.Context, author string, target entities.Target, publicIdentifier string) (*entities.Reminder, error) {
	ret := _m.Called(ctx, author, target, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetReminder")
	}

	var r0 *entities.Reminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Target, string) (*entities.Reminder, error)); ok {
		return rf(ctx, author, target, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Target, string) *entities.Reminder); ok {
		r0 = rf(ctx, author, target, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Reminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entities.Target, string) error); ok {
		r1 = rf(ctx, author, target, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetReminderRepository_GetReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReminder'
type MockGetReminderRepository_GetReminder_Call struct {
	*mock.Call
}

// GetReminder is a helper method to define mock.On call
//   - ctx context.Context
//   - author string
//   - target entities.Target
//   - publicIdentifier string
func (_e *MockGetReminderRepository_Expecter) GetReminder(ctx interface{}, author interface{}, target interface{}, publicIdentifier interface{}) *MockGetReminderRepository_GetReminder_Call {
	return &MockGetReminderRepository_GetReminder_Call{Call: _e.mock.On("GetReminder", ctx, author, target, publicIdentifier)}
}

func (_c *MockGetReminderRepository_GetReminder_Call) Run(run func(ctx context.Context, author string, target entities.Target, publicIdentifier string)) *MockGetReminderRepository_GetReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Target), args[3].(string))
	})
	return _c
}

func (_c *MockGetReminderRepository_GetReminder_Call) Return(_a0 *entities.Reminder, _a1 error) *MockGetReminderRepository_GetReminder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetReminderRepository_GetReminder_Call) RunAndReturn(run func(context.Context, string, entities.Target, string) (*entities.Reminder, error)) *MockGetReminderRepository_GetReminder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetReminderRepository creates a new instance of MockGetReminderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetReminderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetReminderRepository {
	mock := &MockGetReminderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
