// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-reminders/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGetReminderByIDRepository is an autogenerated mock type for the GetReminderByIDRepository type
type MockGetReminderByIDRepository struct {
	mock.Mock
}

type MockGetReminderByIDRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetReminderByIDRepository) EXPECT() *MockGetReminderByIDRepository_Expecter {
	return &MockGetReminderByIDRepository_Expecter{mock: &_m.Mock}
}

// GetReminderByID provides a mock function with given fields: ctx, authorID, reminderID
func (_m *MockGetReminderByIDRepository) GetReminderByID(ctx context.Context, authorID string, reminderID uuid.UUID) (*entities.Reminder, error) {
	ret := _m.Called(ctx, authorID, reminderID)

	if len(ret) == 0 {
		panic("no return value specified for GetReminderByID")
	}

	var r0 *entities.Reminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*entities.Reminder, error)); ok {
		return rf(ctx, authorID, reminderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *entities.Reminder); ok {
		r0 = rf(ctx, authorID, reminderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Reminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, authorID, reminderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetReminderByIDRepository_GetReminderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReminderByID'
type MockGetReminderByIDRepository_GetReminderByID_Call struct {
	*mock.Call
}

// GetReminderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - reminderID uuid.UUID
func (_e *MockGetReminderByIDRepository_Expecter) GetReminderByID(ctx interface{}, authorID interface{}, reminderID interface{}) *MockGetReminderByIDRepository_GetReminderByID_Call {
	return &MockGetReminderByIDRepository_GetReminderByID_Call{Call: _e.mock.On("GetReminderByID", ctx, authorID, reminderID)}
}

func (_c *MockGetReminderByIDRepository_GetReminderByID_Call) Run(run func(ctx context.Context, authorID string, reminderID uuid.UUID)) *MockGetReminderByIDRepository_GetReminderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGetReminderByIDRepository_GetReminderByID_Call) Return(_a0 *entities.Reminder, _a1 error) *MockGetReminderByIDRepository_GetReminderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetReminderByIDRepository_GetReminderByID_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*entities.Reminder, error)) *MockGetReminderByIDRepository_GetReminderByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetReminderByIDRepository creates a new instance of MockGetReminderByIDRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetReminderByIDRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetReminderByIDRepository {
	mock := &MockGetReminderByIDRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
